discord_extensions = (
    "core.controllers.discord.delete",
    "core.controllers.discord.join",
    "core.controllers.discord.leave",
    "core.controllers.discord.logout",
    "core.controllers.discord.ping",
    "core.controllers.discord.tts",
    "core.controllers.discord.poll",
    "core.controllers.discord.roulette",
    "core.controllers.discord.translate",
    "core.controllers.discord.music",
    "core.controllers.discord.tic_tac_toe",
    "core.controllers.discord.feedback",
    "core.controllers.discord.timezone",
    "core.controllers.discord.clock",
)
