"""empty message

Revision ID: 01ca5c43ac9d
Revises: 73bce8369050
Create Date: 2021-12-26 00:20:31.060311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01ca5c43ac9d"
down_revision = "73bce8369050"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discord_bot_logs", sa.Column("guild_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "discord_bot_logs", sa.Column("channel_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discord_bot_logs", "channel_id")
    op.drop_column("discord_bot_logs", "guild_id")
    # ### end Alembic commands ###
