"""Add command_type

Revision ID: a98fe9de1c67
Revises: c1f44c3ebcba
Create Date: 2022-04-24 09:55:53.582098

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a98fe9de1c67"
down_revision = "c1f44c3ebcba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discord_bot_request_logs",
        sa.Column("command_type", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discord_bot_request_logs", "command_type")
    # ### end Alembic commands ###
