"""Add bot_id

Revision ID: 4d725f5aaa69
Revises: 01ca5c43ac9d
Create Date: 2022-04-10 18:24:18.770377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d725f5aaa69"
down_revision = "01ca5c43ac9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discord_bot_logs", sa.Column("bot_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discord_bot_logs", "bot_id")
    # ### end Alembic commands ###
