"""Add timezone

Revision ID: c2482c189142
Revises: a98fe9de1c67
Create Date: 2022-04-24 11:15:26.810033

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2482c189142"
down_revision = "a98fe9de1c67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discord_users",
        sa.Column("timezone", sa.String(), nullable=False, server_default="UTC"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discord_users", "timezone")
    # ### end Alembic commands ###
