"""Add locale

Revision ID: fcdada5cf898
Revises: c2482c189142
Create Date: 2022-12-19 17:51:34.021284

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcdada5cf898"
down_revision = "c2482c189142"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("discord_users", sa.Column("locale", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discord_users", "locale")
    # ### end Alembic commands ###
