"""Rename table

Revision ID: acb836072af7
Revises: 4d725f5aaa69
Create Date: 2022-04-10 18:43:31.449871

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "acb836072af7"
down_revision = "4d725f5aaa69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("discord_bot_logs", "discord_bot_request_logs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("discord_bot_request_logs", "discord_bot_logs")
    # ### end Alembic commands ###
